[context.production.environment]
  HUGO_VERSION = "0.83.1"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.83.1"

[build]
  command = "hugo"
  publish = "public"

[[redirects]]
  from = "/the-economy-of-comfort"
  to = "/services/ductless-split-systems/"

[[redirects]]
  from = "/residential-heating"
  to = "/services/residential-heating/"

[[redirects]]
  from = "/residential-cooling"
  to = "/services/residential-coolingv/"

[[redirects]]
  from = "/indoor-air-quality-services"
  to = "/services/indoor-air-quality-services/"

[[redirects]]
  from = "/reviews"
  to = "/"

[[redirects]]
  from = "/about-us"
  to = "/about/"